### ISSUE TITLE
panics during regular queries

### ISSUE THREAD

**Issue by yurivict** [garak92/rearx#3] opened 2021-03-21 05:16 UTC

**Comment by yurivict** [comment] 2021-03-21 05:16
```
$ rearx "berkeley"

Retrieving page 1...
thread 'main' panicked at '{"query": "berkeley", "number_of_results": 0, "results": [{"title": "Home | University of California, Berkeley", "content": "Berkeley is home to some of the world's greatest minds leading more than 130 academic departments and 80 interdisciplinary research units and addressing the world's most pertinent challenges.", "url": "https://www.berkeley.edu/", "engine": "duckduckgo", "parsed_url": ["https", "www.berkeley.edu", "/", "", "", ""], "engines": ["wikidata", "duckduckgo"], "positions": [1, 1], "score": 8.0, "category": "general", "pretty_url": "https://www.berkeley.edu/"}, {"url": "https://en.wikipedia.org/wiki/Berkeley", "title": "Berkeley", "engine": "ddg definitions", "parsed_url": ["https", "en.wikipedia.org", "/wiki/Berkeley", "", "", ""], "engines": ["ddg definitions"], "positions": [1], "score": 2.0, "category": "general", "pretty_url": "https://en.wikipedia.org/wiki/Berkeley"}, {"url": "http://www.berkeleyplantation.com/", "title": "Berkeley Plantation | HOME", "content": "Berkeley Plantation is the most historic plantation on the James River and is located between Williamsburg and Richmond, Virginia. Berkeley is the site of the first official Thanksgiving as well as the ancestral home of Benjamin Harrison V, a signer of the Declaration of Independence, his son, ninth U.S. President William Henry Harrison, and his grandson, Benjamin Harrison, the twenty-third ...", "engine": "yahoo", "parsed_url": ["http", "www.berkeleyplantation.com", "/", "", "", ""], "engines": ["yahoo"], "positions": [1], "score": 1.0, "category": "general", "pretty_url": "http://www.berkeleyplantation.com/"}, {"title": "University of California, Berkeley", "url": "https://en.wikipedia.org/wiki/University_of_California,_Berkeley", "engine": "wikidata", "parsed_url": ["https", "en.wikipedia.org", "/wiki/University_of_California,_Berkeley", "", "", ""], "engines": ["wikidata"], "positions": [2], "score": 1.0, "category": "general", "pretty_url": "https://en.wikipedia.org/wiki/University_of_California,_Berkeley"}, {"title": "UC Berkeley - Home | Facebook", "content": "UC Berkeley, Berkeley, California. 483,535 likes \u00b7 4,165 talking about this. The official page of the University of California, Berkeley, the premier...", "url": "https://www.facebook.com/UCBerkeley/", "engine": "duckduckgo", "parsed_url": ["https", "www.facebook.com", "/UCBerkeley/", "", "", ""], "engines": ["duckduckgo"], "positions": [2], "score": 0.5, "category": "general", "pretty_url": "https://www.facebook.com/UCBerkeley/"}, {"url": "http://studyabroad.berkeley.edu/", "title": "Welcome | UCB Study Abroad", "content": "Berkeley is #1 in Gilman Scholarship recipients and our Berkeley Study Abroad Scholarship is available to a broad range of students. Will I graduate on time? With advanced planning and coordination with your college and department(s) you can apply courses taken on study abroad to your major, minor, breadth, and general education requirements ...", "engine": "yahoo", "parsed_url": ["http", "studyabroad.berkeley.edu", "/", "", "", ""], "engines": ["yahoo"], "positions": [2], "score": 0.5, "category": "general", "pretty_url": "http://studyabroad.berkeley.edu/"}, {"title": "Berkeley, California - Wikipedia", "content": "Berkeley (/\u02c8b\u025c\u02d0rkli/ BURK-lee) is a city on the eastern shore of San Francisco Bay in northern Alameda County, California. It is named after the 18th-century Irish bishop and philosopher George Berkeley.", "url": "https://en.wikipedia.org/wiki/Berkeley,_California", "engine": "duckduckgo", "parsed_url": ["https", "en.wikipedia.org", "/wiki/Berkeley,_California", "", "", ""], "engines": ["duckduckgo"], "positions": [3], "score": 0.3333333333333333, "category": "general", "pretty_url": "https://en.wikipedia.org/wiki/Berkeley,_California"}, {"url": "https://boinc.berkeley.edu/", "title": "BOINC", "content": "The BOINC and Science United projects are located at the University of California, Berkeley and are supported by the National Science Foundation. START COMPUTING! To contribute to science areas (biomedicine, physics, astronomy, and so on) use Science United .", "engine": "yahoo", "parsed_url": ["https", "boinc.berkeley.edu", "/", "", "", ""], "engines": ["yahoo"], "positions": [3], "score": 0.3333333333333333, "category": "general", "pretty_url": "https://boinc.berkeley.edu/"}, {"title": "UC Berkeley (@ucberkeleyofficial) \u2022 \u0424\u043e\u0442\u043e \u0438 \u0432\u0438\u0434\u0435\u043e \u0432 Instagram", "content": "The official account for UC Berkeley. UC Berkeley. \u041f\u043e\u0434\u043f\u0438\u0441\u0430\u0442\u044c\u0441\u044f. caladmissions. \u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u043d\u044b\u0439. UC Berkeley Admissions.", "url": "https://www.instagram.com/ucberkeleyofficial/", "engine": "duckduckgo", "parsed_url": ["https", "www.instagram.com", "/ucberkeleyofficial/", "", "", ""], "engines": ["duckduckgo"], "positions": [4], "score": 0.25, "category": "general", "pretty_url": "https://www.instagram.com/ucberkeleyofficial/"}, {"url": "http://oskicat.berkeley.edu/search", "title": "Search | Oskicat - University of California, Berkeley", "content": "We would like to show you a description here but the site won\u2019t allow us.", "engine": "yahoo", "parsed_url": ["http", "oskicat.berkeley.edu", "/search", "", "", ""], "engines": ["yahoo"], "positions": [4], "score": 0.25, "category": "general", "pretty_url": "http://oskicat.berkeley.edu/search"}, {"title": "UC Berkeley (@UCBerkeley) | \u0422\u0432\u0438\u0442\u0442\u0435\u0440", "content": "\u041f\u043e\u0441\u043b\u0435\u0434\u043d\u0438\u0435 \u0442\u0432\u0438\u0442\u044b \u043e\u0442 UC Berkeley (@UCBerkeley). Official account of the University of California, Berkeley. \"Bk\" stands for Berkelium, one of the 16 elements discovered here.", "url": "https://twitter.com/UCBerkeley", "engine": "duckduckgo", "parsed_url": ["https", "twitter.com", "/UCBerkeley", "", "", ""], "engines": ["duckduckgo"], "positions": [5], "score": 0.2, "category": "general", "pretty_url": "https://twitter.com/UCBerkeley"}, {"url": "https://coolclimate.berkeley.edu/calculator", "title": "CoolClimate Calculator - University of California, Berkeley", "content": "Calculate and compare your carbon footprint to similar households and create a personalized climate action plan", "engine": "yahoo", "parsed_url": ["https", "coolclimate.berkeley.edu", "/calculator", "", "", ""], "engines": ["yahoo"], "positions": [5], "score": 0.2, "category": "general", "pretty_url": "https://coolclimate.berkeley.edu/calculator"}, {"title": "University of California, Berkeley - 2021 All You Need to... - Tripadvisor", "content": "Popular Berkeley Categories. Berkeley Downtown Hotels. Hotels near University of California, Berkeley. Hotels near Tilden Regional Park.", "url": "https://www.tripadvisor.com/Attraction_Review-g32066-d117244-Reviews-University_of_California_Berkeley-Berkeley_California.html", "engine": "duckduckgo", "parsed_url": ["https", "www.tripadvisor.com", "/Attraction_Review-g32066-d117244-Reviews-University_of_California_Berkeley-Berkeley_California.html", "", "", ""], "engines": ["duckduckgo"], "positions": [6], "score": 0.16666666666666666, "category": "general", "pretty_url": "https://www.tripadvisor.com/Attraction[...]rnia_Berkeley-Berkeley_California.html"}, {"url": "http://mcb.berkeley.edu/", "title": "Department of Molecular & Cell Biology", "content": "Why did you decide to apply to UCB? I wanted to apply to UC Berkeley because this university is recognized for its prestigious research programs and I this was one of the few schools that offered my major that I was interested in pursuing. I am a commuter student and I am fortunate that I live close to the campus so that I can participate in my extracurriculars and have", "engine": "yahoo", "parsed_url": ["http", "mcb.berkeley.edu", "/", "", "", ""], "engines": ["yahoo"], "positions": [6], "score": 0.16666666666666666, "category": "general", "pretty_url": "http://mcb.berkeley.edu/"}, {"title": "Berklee Homepage | Berklee", "content": "Berklee is the premier institute of music and the performing arts, offering degrees at its campuses in Boston, New York City, and Valencia, Spain, and online.", "url": "https://www.berklee.edu/", "engine": "duckduckgo", "parsed_url": ["https", "www.berklee.edu", "/", "", "", ""], "engines": ["duckduckgo"], "positions": [7], "score": 0.14285714285714285, "category": "general", "pretty_url": "https://www.berklee.edu/"}, {"url": "https://callink.berkeley.edu/", "title": "- CalLink at UC Berkeley", "content": "\u00a9 Campus Labs 2021", "engine": "yahoo", "parsed_url": ["https", "callink.berkeley.edu", "/", "", "", ""], "engines": ["yahoo"], "positions": [7], "score": 0.14285714285714285, "category": "general", "pretty_url": "https://callink.berkeley.edu/"}, {"title": "Berkeley, George | Internet Encyclopedia of Philosophy", "content": "Berkeley's empirical theory of vision challenged the then-standard account of distance vision, an Berkeley argues that the visual perception of distance is explained by the correlation of ideas of sight...", "url": "https://iep.utm.edu/berkeley/", "engine": "duckduckgo", "parsed_url": ["https", "iep.utm.edu", "/berkeley/", "", "", ""], "engines": ["duckduckgo"], "positions": [8], "score": 0.125, "category": "general", "pretty_url": "https://iep.utm.edu/berkeley/"}, {"url": "https://csmentors.berkeley.edu/", "title": "Computer Science Mentors - University of California, Berkeley", "content": "Computer Science Mentors \u2014 UC Berkeley", "engine": "yahoo", "parsed_url": ["https", "csmentors.berkeley.edu", "/", "", "", ""], "engines": ["yahoo"], "positions": [8], "score": 0.125, "category": "general", "pretty_url": "https://csmentors.berkeley.edu/"}, {"title": "University of California--Berkeley - Profile... | US News Best Colleges", "content": "Berkeley has 14 schools and colleges, including a number of graduate and professional schools, such as the Berkeley is well known as a hub of liberal student activism: The Free Speech Movement - a...", "url": "https://www.usnews.com/best-colleges/university-of-california-berkeley-1312", "engine": "duckduckgo", "parsed_url": ["https", "www.usnews.com", "/best-colleges/university-of-california-berkeley-1312", "", "", ""], "engines": ["duckduckgo"], "positions": [9], "score": 0.1111111111111111, "category": "general", "pretty_url": "https://www.usnews.com/best-colleges/u[...]university-of-california-berkeley-1312"}, {"url": "http://precollege.berkeley.edu/", "title": "PreCollege Programs - University of California, Berkeley", "content": "Offered virtually for summer 2021. Be part of UC Berkeley\u2019s virtual campus this summer and attend the Pre-College Scholars: Summer Virtual program which offers high school students the opportunity to enroll in online courses while earning UC Berkeley credit.", "engine": "yahoo", "parsed_url": ["http", "precollege.berkeley.edu", "/", "", "", ""], "engines": ["yahoo"], "positions": [9], "score": 0.1111111111111111, "category": "general", "pretty_url": "http://precollege.berkeley.edu/"}, {"title": "University of California, Berkeley", "content": "Berkeley graduates go on to be leaders in their field. The university boasts numerous notable alumni such as the cofounder of Apple Steve Wozniak, the cofounder of Intel Corporation Gordon Moore...", "url": "https://www.forbes.com/colleges/university-of-california-berkeley/", "engine": "duckduckgo", "parsed_url": ["https", "www.forbes.com", "/colleges/university-of-california-berkeley/", "", "", ""], "engines": ["duckduckgo"], "positions": [10], "score": 0.1, "category": "general", "pretty_url": "https://www.forbes.com/colleges/university-of-california-berkeley/"}, {"url": "https://hearstmuseum.berkeley.edu/", "title": "Home \u2013 Phoebe A. Hearst Museum of Anthropology", "content": "Our Mission. To steward a vast collection of objects spanning the infinite breadth of human cultures for the advancement of knowledge and understanding", "engine": "yahoo", "parsed_url": ["https", "hearstmuseum.berkeley.edu", "/", "", "", ""], "engines": ["yahoo"], "positions": [10], "score": 0.1, "category": "general", "pretty_url": "https://hearstmuseum.berkeley.edu/"}, {"title": "Berkeley, California Official Tourism Site - Visit Berkeley", "content": "Discover your Berkeley. From vibrant Downtown Berkeley to the storied history of Telegraph Avenue, there is something to do for the Berkeley in everyone.", "url": "https://www.visitberkeley.com/", "engine": "duckduckgo", "parsed_url": ["https", "www.visitberkeley.com", "/", "", "", ""], "engines": ["duckduckgo"], "positions": [11], "score": 0.09090909090909091, "category": "general", "pretty_url": "https://www.visitberkeley.com/"}, {"title": "Berkeley", "content": "A subreddit for the community of UC Berkeley as well as the surrounding City of Berkeley, California.", "url": "https://www.reddit.com/r/berkeley/", "engine": "duckduckgo", "parsed_url": ["https", "www.reddit.com", "/r/berkeley/", "", "", ""], "engines": ["duckduckgo"], "positions": [12], "score": 0.08333333333333333, "category": "general", "pretty_url": "https://www.reddit.com/r/berkeley/"}, {"title": "Berkeley College | Degree & Certificate Programs in NJ, NY & Online", "content": "Find out what's going on around Berkeley College. Connect with us, find the degree and certificate programs we offer, or read up on Berkeley news.", "url": "https://berkeleycollege.edu/", "engine": "duckduckgo", "parsed_url": ["https", "berkeleycollege.edu", "/", "", "", ""], "engines": ["duckduckgo"], "positions": [13], "score": 0.07692307692307693, "category": "general", "pretty_url": "https://berkeleycollege.edu/"}, {"title": "berkeleygroup.co.uk", "content": "Berkeley Eastern Counties - Hollyfields.", "url": "https://www.berkeleygroup.co.uk/", "engine": "duckduckgo", "parsed_url": ["https", "www.berkeleygroup.co.uk", "/", "", "", ""], "engines": ["duckduckgo"], "positions": [14], "score": 0.07142857142857142, "category": "general", "pretty_url": "https://www.berkeleygroup.co.uk/"}, {"title": "Berkeleyside \u2014 Berkeley, CA's independent news site", "content": "Berkeleyside is the leading local news source for breaking news, public safety, politics, food, real estate and development, education and more in Berkeley, California.", "url": "https://www.berkeleyside.com/", "engine": "duckduckgo", "parsed_url": ["https", "www.berkeleyside.com", "/", "", "", ""], "engines": ["duckduckgo"], "positions": [15], "score": 0.06666666666666667, "category": "general", "pretty_url": "https://www.berkeleyside.com/"}, {"title": "University of California - Berkeley - Niche", "content": "UC Berkeley is a highly rated public university located in Berkeley, California in the San Francisco Bay Area. Admissions is competitive as the UC Berkeley acceptance rate is 16%.", "url": "https://www.niche.com/colleges/university-of-california---berkeley/", "engine": "duckduckgo", "parsed_url": ["https", "www.niche.com", "/colleges/university-of-california---berkeley/", "", "", ""], "engines": ["duckduckgo"], "positions": [16], "score": 0.0625, "category": "general", "pretty_url": "https://www.niche.com/colleges/university-of-california---berkeley/"}, {"title": "Berkeleytime", "content": "Berkeley's online course discovery platform. Berkeleytime is a platform built, maintained, and run by students, just like you. We work hard to simplify and improve the course discovery experience.", "url": "https://berkeleytime.com/", "engine": "duckduckgo", "parsed_url": ["https", "berkeleytime.com", "/", "", "", ""], "engines": ["duckduckgo"], "positions": [17], "score": 0.058823529411764705, "category": "general", "pretty_url": "https://berkeleytime.com/"}, {"title": "University of California, Berkeley | edX", "content": "Berkeley faculty consists of 1,582 full-time and 500 part-time faculty members dispersed among more than 130 academic departments and more than 80 interdisciplinary research units.", "url": "https://www.edx.org/school/uc-berkeleyx", "engine": "duckduckgo", "parsed_url": ["https", "www.edx.org", "/school/uc-berkeleyx", "", "", ""], "engines": ["duckduckgo"], "positions": [18], "score": 0.05555555555555555, "category": "general", "pretty_url": "https://www.edx.org/school/uc-berkeleyx"}], "answers": [], "corrections": [], "infoboxes": [{"infobox": "Berkeley", "id": "https://en.wikipedia.org/wiki/Berkeley", "content": "", "img_src": null, "attributes": [], "urls": [{"title": "Wikipedia", "url": "https://en.wikipedia.org/wiki/Berkeley", "official": true}], "relatedTopics": [{"name": "Places", "suggestions": ["Berkeley, New South Wales", "Berkeley, Ontario", "Berkeley (hundred)", "Berkeley, Gloucestershire", "Berkeley, Denver", "Berkeley, Illinois", "Berkeley, Missouri", "Berkeley Township, Ocean County, New Jersey", "Berkeley, Rhode Island", "Berkeley, West Virginia"]}, {"name": "People", "suggestions": ["Berkeley family"]}, {"name": "Brands and enterprises", "suggestions": ["Berkeley (1913)", "Berkeley Cars", "Berkeley Cinemas", "Berkeley Group Holdings", "Berkeley Systems"]}, {"name": "Hotels", "suggestions": ["The Berkeley", "The Berkeley, Scunthorpe"]}, {"name": "Schools", "suggestions": ["Berkeley Adult School", "Berkeley City College", "Berkeley College (Yale University)", "Berkeley College", "Berklee College of Music", "Berkeley County Schools"]}, {"name": "Ships", "suggestions": ["Berkeley (ferryboat)"]}, {"name": "Software", "suggestions": ["Berkeley DB", "Berkeley Fast File System", "Berkeley Software Distribution"]}, {"name": "Other uses", "suggestions": ["Berkeley (film)", "Berkeley Hundred", "Berkeley Hunt", "Berkeley National Laboratory", "Berkeley Test"]}, {"name": "See also", "suggestions": ["Berkeley Building", "Berkelium", "Berkeley, Virginia Meanings", "Berkeley County Meanings", "Berkeley (given name) Meanings", "Berkeley (surname) Meanings", "Berkeley High School Meanings", "HMS Berkeley Castle Meanings", "Barkley Meanings", "Berkley Meanings", "Barclay Meanings", "Berkeley Group Meanings", "Berkeley House Meanings", "Berkeley Square Meanings", "Berkeley station Meanings"]}], "engine": "ddg definitions", "engines": ["ddg definitions"]}, {"infobox": "University of California, Berkeley", "id": "https://en.wikipedia.org/wiki/University_of_California,_Berkeley", "content": "public research university in Berkeley, California, United States", "img_src": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20University%20of%20California%2C%20Berkeley.svg?width=500&height=400", "urls": [{"title": "P856", "url": "https://www.berkeley.edu", "official": true}, {"title": "Wikipedia (en)", "url": "https://en.wikipedia.org/wiki/University_of_California,_Berkeley"}, {"title": "Twitter", "url": "https://twitter.com/UCBerkeley"}, {"title": "Facebook", "url": "https://facebook.com/UCBerkeley"}, {"title": "OpenStreetMap", "url": "https://www.openstreetmap.org/?lat=37.87&lon=-122.259&zoom=19&layers=M", "entity": "P625"}, {"title": "Wikidata", "url": "http://www.wikidata.org/entity/Q168756"}], "attributes": [{"label": "P571", "value": "Monday, March 23, 1868", "entity": "P571"}, {"label": "P17", "value": "United States of America", "entity": "P17"}, {"label": "P159", "value": "Berkeley", "entity": "P159"}, {"label": "P281", "value": "94720", "entity": "P281"}], "engine": "wikidata", "engines": ["wikidata"]}], "suggestions": ["berkeley used cars", "Berkeley, California", "berkeley university", "berkeley county school district", "George Berkeley", "george berkeley", "Berklee College of Music", "berkeley philosopher", "University of California, Berkeley", "berkeley weather", "berkeley public library", "berkeley college"], "unresponsive_engines": []}: reqwest::Error { kind: Decode, source: Error("missing field `content`", line: 1, column: 899) }', src/request.rs:19:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by garak92** [comment] 2021-03-21 14:07
Hello. I've been able to reproduce this behavior, and it is not intended. I will be shipping a fix as soon as I can.

Thank you for pointing this out.

**Comment by garak92** [comment] 2021-03-22 22:45
Fixed on [https://github.com/garak92/rearx/commit/35fc0ac90580594ef61aa8fbcc49736f7907be05](this commit)

**Closed by garak92** 2021-03-22 22:45 UTC
